import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Syne, Hanken_Grotesk } from "next/font/google";
import { ThemeProvider } from "next-themes";
import Header from "@/components/Global/Header";
import Footer from "@/components/Global/Footer";


const syne = Syne({ subsets: ["latin"], variable: "--font-syne" });
const hanken = Hanken_Grotesk({ subsets: ["latin"], variable: "--font-hanken" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning className={`${syne.variable} ${hanken.variable}`}
    >
      <body className="min-h-full flex flex-col">

        <ThemeProvider
          attribute="data-theme"
          themes={["light", "dark", "contrast"]}
          defaultTheme="system"
          enableSystem
        >
          <Header />
          <main id="top">
            {children}
            <Footer />
          </main>
        </ThemeProvider>

      </body>
    </html>
  );
}
